DiskError_00	db	"Nedoçlo k § dn‚ chybØ",0
DiskError_01	db	"Neplatnì po§adavek na ýadiŸ %",0
DiskError_02	db	"Chybn  adresov  znaŸka sektoru disku %",0
DiskError_03	db	"Pokus o z pis na disk % chr nØnì proti z pisu",0
DiskError_04	db	"Sektor na disku % nenalezen",0
DiskError_05	db	"Chyba pýi resetov n¡ ýadiŸe %",0
DiskError_06	db	"Disketa % byla vymØnØna",0
DiskError_07	db	"Chybnì parametr pýi pr ci s diskem %",0
DiskError_08    db      "Chyba DMA (overrun)na disku %",0
DiskError_09    db      "PýeteŸen¡ DMA pýes 64KB pýi pr ci s diskem %",0
DiskError_0A    db      "U pevn‚ho disku % detekov n chybnì sektor",0
DiskError_0B    db      "U pevn‚ho disku % detekov na chybn  stopa",0
DiskError_0C    db      "Nepodporovan  stopa na disku %",0
DiskError_0D    db      "Chybnì poŸet sektor… pýi form tov n¡ pevn‚ho disku %",0
DiskError_0E    db      "U pevn‚ho disku % detekov na adresov  znaŸka kontroln¡ch dat",0
DiskError_0F    db      "U pevn‚ho disku % doçlo k chybØ v rozhodov n¡ DMA",0
DiskError_10    db      "æpatn  parita CRC/ECC na disku %",0
DiskError_11    db      "Chybn  data byla u pevn‚ho disku % opravena pomoc¡ ECC",0
DiskError_20    db      "Chyba ýadiŸe %",0
DiskError_40    db      "Chybnì seek (chyba pýi vystavov n¡ hlaviŸek) na disku %",0
DiskError_80    db      "Disk % nen¡ pýipraven",0
DiskError_0AA   db      "Pevnì % disk nen¡ pýipraven",0
DiskError_0BB   db      "Nezn m  diskov  chyba pýi pr ci s pevnìm diskem %",0
DiskError_0CC   db      "U pevn‚ho disku % doçlo k chybØ z pisu",0
DiskError_0E0   db      "U pevn‚ho disku % doçlo k chybØ stavov‚ho registru",0
DiskError_0FF   db      "U pevn‚ho disku % byl pou§it chybnì vìznam operace",0
DiskError_N     db      "Pýi pr ci s diskem % vznikl nezn mì chybovì k¢d %",0
